### ISSUE TITLE
Models not found!

### ISSUE THREAD

**Issue by iamvc7** [MDBox/deeplens-simon-says#1]
Can you please make the models available ?

**Comment by MDBox** [comment]
Sorry about that Zzoey.  I will update the links later this week.  You can also download the original models from https://github.com/dragonfly90/mxnet_Realtime_Multi-Person_Pose_Estimation or https://github.com/CMU-Perceptual-Computing-Lab/openpose and convert them to work on the deeplens that is what we did.

**Comment by lciruelo** [comment]
Hi, I cant get faster_184.xml model file.
The code reference the model file to /home/aws_cam/ but in my AWS DeepLens, aws_cam library is installed on /opt/, without that model file.
How can i get the model?

thanks

**Comment by MDBox** [comment]
Sorry for my delay.  I uploaded them to a google drive.  https://drive.google.com/drive/folders/1F9yocDWibUf1Q0_J7LdOAkIrJIVPso6G
